"""Emit a self-contained, runnable Jupyter notebook from a pipeline run.

Generates context-aware cells based on:
  - Whether a target column is set (full pipeline vs EDA-only)
  - Task type (classification vs regression vs clustering)
  - Available artifacts (profile, quality, MI, features, train, drift)
  - The PDF brief (used in the header for domain context)
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

# ── cell helpers ──────────────────────────────────────────────────────────────

def _md(text: str) -> dict[str, Any]:
    return {"cell_type": "markdown", "metadata": {},
            "source": text.splitlines(keepends=True) or [""]}


def _code(src: str) -> dict[str, Any]:
    return {"cell_type": "code", "metadata": {}, "execution_count": None,
            "outputs": [], "source": src.splitlines(keepends=True) or [""]}


def _fmt_metrics(d: dict[str, Any]) -> str:
    return "\n".join(
        f"  - **{k}**: {v:.4f}" if isinstance(v, float) else f"  - **{k}**: {v}"
        for k, v in d.items()
    )


# ── public entry point ────────────────────────────────────────────────────────

def build(
    *,
    data_path: Path,
    target: str | None,
    brief: str,
    artifacts: dict[str, Any],
    out_path: Path,
) -> Path:
    """Write a rich, runnable notebook to `out_path`."""
    cells: list[dict[str, Any]] = []
    tgt = target or ""
    eda_only = not bool(tgt)

    task_data = artifacts.get("task", {}) or {}
    task_type = (task_data.get("task") or "").lower()
    is_regression = "regression" in task_type
    is_clustering = "clustering" in task_type
    _is_classif = (not is_regression) and (not is_clustering) and (not eda_only)  # noqa: F841

    train = artifacts.get("train", {}) or {}
    prof = artifacts.get("profile", {}) or {}
    qual = artifacts.get("quality", {}) or {}
    mi = artifacts.get("mi", {}) or {}
    feats = artifacts.get("features", {}) or {}
    sel = artifacts.get("selected_features", {}) or {}
    drift = artifacts.get("drift", {}) or {}

    suffix = data_path.suffix.lower()

    # ── 0. Title & brief ─────────────────────────────────────────────────
    mode_label = "EDA" if eda_only else f"Full pipeline — {task_type or 'classification'}"
    cells.append(_md(
        f"# Data Science Report — ds-agent\n\n"
        f"| | |\n|---|---|\n"
        f"| **Data file** | `{data_path}` |\n"
        f"| **Target** | `{tgt or '(not set — EDA only)'}` |\n"
        f"| **Mode** | {mode_label} |\n"
        f"| **Generated by** | ds-agent v0.1.0 |\n"
    ))

    if brief.strip():
        snippet = brief.strip()[:3000] + ("\n\n*[brief truncated]*" if len(brief) > 3000 else "")
        cells.append(_md(f"## 0. Project brief (from PDF)\n\n{snippet}"))

    # ── 1. Imports & setup ───────────────────────────────────────────────
    cells.append(_md("## 1. Setup"))
    cells.append(_code(
        "import warnings\n"
        "warnings.filterwarnings('ignore')\n"
        "import pandas as pd\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "import matplotlib.ticker as mticker\n"
        "import seaborn as sns\n"
        "from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold\n"
        "from sklearn.preprocessing import LabelEncoder, StandardScaler\n"
        "from sklearn.impute import SimpleImputer\n"
        "from sklearn.pipeline import Pipeline\n"
        "from sklearn.metrics import (\n"
        "    classification_report, confusion_matrix, roc_auc_score,\n"
        "    ConfusionMatrixDisplay, RocCurveDisplay,\n"
        "    mean_absolute_error, mean_squared_error, r2_score,\n"
        ")\n"
        "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n"
        "from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor\n"
        "from sklearn.linear_model import LogisticRegression, Ridge\n"
        "pd.set_option('display.max_columns', 60)\n"
        "pd.set_option('display.float_format', '{:.4f}'.format)\n"
        f"TARGET = {repr(tgt) if tgt else 'None'}  # set to None for EDA-only mode\n"
    ))

    # ── 2. Load data ─────────────────────────────────────────────────────
    cells.append(_md("## 2. Load data"))
    load_code = (
        "import pandas as pd\n"
        f"df = pd.read_{'parquet' if suffix == '.parquet' else 'csv'}(r'{data_path}')\n"
        "print(f'Shape: {df.shape}')\n"
        "print(f'Columns: {df.columns.tolist()}')\n"
        "df.head()"
    )
    cells.append(_code(load_code))

    # ── 3. Profile summary ───────────────────────────────────────────────
    if prof:
        # Profiler returns {profile:[col dicts], n_rows, n_cols, overall_null_rate, duplicate_rows}
        n_rows = prof.get("n_rows", "?")
        n_cols = prof.get("n_cols", "?")
        null_rate = prof.get("overall_null_rate", 0)
        dups = prof.get("duplicate_rows", "?")
        cells.append(_md(
            f"## 3. Data profile\n\n"
            f"| Metric | Value |\n|---|---|\n"
            f"| Rows | **{n_rows:,}** |\n"
            f"| Columns | **{n_cols}** |\n"
            f"| Overall null rate | **{float(null_rate or 0):.2%}** |\n"
            f"| Duplicate rows | **{dups}** |\n"
        ))
    cells.append(_code(
        "# Column-level summary\n"
        "summary = pd.DataFrame({\n"
        "    'dtype': df.dtypes.astype(str),\n"
        "    'null_count': df.isna().sum(),\n"
        "    'null_pct': (df.isna().mean() * 100).round(2),\n"
        "    'n_unique': df.nunique(),\n"
        "})\n"
        "summary['sample_values'] = [df[c].dropna().unique()[:3].tolist() for c in df.columns]\n"
        "summary.sort_values('null_pct', ascending=False)"
    ))

    # ── 4. Data quality ──────────────────────────────────────────────────
    if qual:
        score = qual.get("score") or qual.get("overall_score", "?")
        dims = qual.get("dimensions", {})
        dim_rows = "\n".join(f"  - **{k}**: {v:.4f}" if isinstance(v, float) else f"  - **{k}**: {v}"
                             for k, v in dims.items()) if dims else ""
        cells.append(_md(
            f"## 4. Data quality\n\n"
            f"Overall quality score: **{score}**\n\n"
            + (dim_rows or "_(no dimension scores)_")
        ))
    cells.append(_code(
        "# Missing value heatmap (sample)\n"
        "sample = df.sample(min(len(df), 500), random_state=0)\n"
        "fig, ax = plt.subplots(figsize=(14, 5))\n"
        "sns.heatmap(sample.isna(), cbar=False, yticklabels=False, ax=ax,\n"
        "            cmap=['#1a1d24', '#ffd57a'])\n"
        "ax.set_title('Missing value map (yellow = missing)')\n"
        "plt.tight_layout(); plt.show()\n"
        "\n"
        "# Duplicate check\n"
        "print(f'Duplicate rows: {df.duplicated().sum()} / {len(df)}')\n"
        "df = df.drop_duplicates().reset_index(drop=True)\n"
        "print(f'Shape after dedup: {df.shape}')"
    ))

    # ── 5. EDA ───────────────────────────────────────────────────────────
    cells.append(_md("## 5. Exploratory data analysis"))

    # 5a numeric distributions
    cells.append(_code(
        "num_cols = df.select_dtypes('number').columns.tolist()\n"
        "if TARGET: num_cols = [c for c in num_cols if c != TARGET]\n"
        "print(f'{len(num_cols)} numeric features')\n"
        "df[num_cols].describe().T[['mean','std','min','25%','50%','75%','max']]"
    ))
    cells.append(_code(
        "# Distribution histograms\n"
        "n = len(num_cols[:16])\n"
        "if n > 0:\n"
        "    ncols = min(4, n); nrows = (n + ncols - 1) // ncols\n"
        "    fig, axes = plt.subplots(nrows, ncols, figsize=(16, 3 * nrows))\n"
        "    axes = np.array(axes).flatten()\n"
        "    for i, col in enumerate(num_cols[:16]):\n"
        "        df[col].dropna().hist(bins=40, ax=axes[i], color='#4d7cc7')\n"
        "        axes[i].set_title(col, fontsize=9)\n"
        "        axes[i].tick_params(labelsize=7)\n"
        "    for j in range(i + 1, len(axes)): axes[j].set_visible(False)\n"
        "    plt.suptitle('Numeric feature distributions', y=1.01)\n"
        "    plt.tight_layout(); plt.show()"
    ))

    # 5b categorical
    cells.append(_code(
        "cat_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()\n"
        "if TARGET and TARGET in cat_cols: cat_cols.remove(TARGET)\n"
        "print(f'{len(cat_cols)} categorical features')\n"
        "# Top-10 value counts for each low-cardinality column\n"
        "for col in cat_cols[:6]:\n"
        "    if df[col].nunique() <= 30:\n"
        "        fig, ax = plt.subplots(figsize=(8, 3))\n"
        "        df[col].value_counts().head(10).plot(kind='barh', ax=ax, color='#4d7cc7')\n"
        "        ax.set_title(f'{col} — top 10 values'); ax.invert_yaxis()\n"
        "        plt.tight_layout(); plt.show()"
    ))

    # 5c correlation heatmap
    cells.append(_code(
        "if len(num_cols) > 1:\n"
        "    corr = df[num_cols].corr()\n"
        "    mask = np.triu(np.ones_like(corr, dtype=bool))\n"
        "    fig, ax = plt.subplots(figsize=(min(14, len(num_cols)), min(12, len(num_cols))))\n"
        "    sns.heatmap(corr, mask=mask, annot=len(num_cols) <= 15, fmt='.2f',\n"
        "                cmap='coolwarm', center=0, linewidths=0.5, ax=ax)\n"
        "    ax.set_title('Correlation heatmap (lower triangle)')\n"
        "    plt.tight_layout(); plt.show()"
    ))

    # 5d target distribution (classification)
    if tgt:
        cells.append(_md(f"### 5d. Target distribution — `{tgt}`"))
        cells.append(_code(
            "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n"
            "vc = df[TARGET].value_counts()\n"
            "vc.plot(kind='bar', ax=axes[0], color='#4d7cc7')\n"
            "axes[0].set_title('Class counts')\n"
            "axes[0].set_xlabel(TARGET)\n"
            "vc.plot(kind='pie', ax=axes[1], autopct='%1.1f%%', startangle=90)\n"
            "axes[1].set_title('Class proportion')\n"
            "axes[1].set_ylabel('')\n"
            "plt.tight_layout(); plt.show()\n"
            "print(df[TARGET].value_counts(normalize=True).rename('proportion'))"
        ))

    # 5e MI
    mi_scores = mi.get("scores") if isinstance(mi, dict) else None
    if mi_scores:
        if isinstance(mi_scores, dict):
            top_mi = sorted(mi_scores.items(), key=lambda x: -float(x[1] or 0))[:15]
            mi_rows = "\n".join(f"  - `{k}` — MI {float(v):.4f}" for k, v in top_mi)
        elif isinstance(mi_scores, list):
            top_mi = sorted(mi_scores, key=lambda x: -float(x.get("mi", 0)))[:15]
            mi_rows = "\n".join(
                f"  - `{s.get('feature','?')}` — MI {float(s.get('mi',0)):.4f}"
                for s in top_mi
            )
        else:
            mi_rows = ""
        if mi_rows:
            cells.append(_md(f"### 5e. Mutual information vs `{tgt}`\n\n{mi_rows}"))
        cells.append(_code(
            "from sklearn.feature_selection import mutual_info_classif, mutual_info_regression\n"
            "num_feats = df.select_dtypes('number').columns.tolist()\n"
            f"if TARGET and TARGET in num_feats: num_feats.remove(TARGET)\n"
            "X_mi = df[num_feats].fillna(df[num_feats].median())\n"
            f"y_mi = df[TARGET].fillna(df[TARGET].mode()[0]) if TARGET else None\n"
            "if TARGET and y_mi is not None:\n"
            f"    fn = mutual_info_{'regression' if is_regression else 'classif'}\n"
            "    mi_vals = fn(X_mi, y_mi, random_state=0)\n"
            "    mi_s = pd.Series(mi_vals, index=num_feats).sort_values(ascending=False)\n"
            "    mi_s.head(20).plot(kind='barh', figsize=(8, 6), color='#4d7cc7')\n"
            "    plt.title(f'Mutual information vs {TARGET}')\n"
            "    plt.gca().invert_yaxis(); plt.tight_layout(); plt.show()\n"
            "    print(mi_s.head(20))"
        ))

    # ── 6. Feature engineering & preprocessing ───────────────────────────
    cells.append(_md("## 6. Feature engineering & preprocessing"))
    if sel:
        selected = sel.get("selected", [])[:30]
        cells.append(_md(
            f"Feature selection ({sel.get('method','?')}) kept "
            f"**{sel.get('n_selected', len(selected))}** features.\n\n"
            f"Top features: `{selected[:15]}`"
        ))
    if feats:
        new_f = feats.get("new_features", [])[:15]
        cells.append(_md(
            f"Feature generation added interactions/polynomials. "
            f"New features: `{new_f}`"
        ))

    fe_code = (
        "from sklearn.impute import SimpleImputer\n"
        "from sklearn.preprocessing import OneHotEncoder\n"
        "from sklearn.compose import ColumnTransformer\n"
        "from sklearn.pipeline import Pipeline\n"
        "\n"
        "num_feats = df.select_dtypes('number').columns.tolist()\n"
        "cat_feats = df.select_dtypes(include=['object','category']).columns.tolist()\n"
        + ("if TARGET in num_feats: num_feats.remove(TARGET)\n"
           "if TARGET in cat_feats: cat_feats.remove(TARGET)\n" if tgt else "")
        + "\n"
        "# Keep only low-cardinality categoricals for one-hot encoding\n"
        "cat_feats_ohe = [c for c in cat_feats if df[c].nunique() <= 20]\n"
        "\n"
        "preprocessor = ColumnTransformer([\n"
        "    ('num', SimpleImputer(strategy='median'), num_feats),\n"
        "    ('cat', Pipeline([('imp', SimpleImputer(strategy='most_frequent')),\n"
        "                      ('ohe', OneHotEncoder(handle_unknown='ignore',\n"
        "                                            sparse_output=False))]),\n"
        "           cat_feats_ohe),\n"
        "], remainder='drop')\n"
        "\n"
        + (
            # Drop rows with NaN target BEFORE splitting X and y
            "# Drop rows with missing target (avoids NaN-in-y training errors)\n"
            "_target_null = df[TARGET].isna()\n"
            "if _target_null.any():\n"
            "    print(f'Dropping {_target_null.sum()} rows with NaN target')\n"
            "    df = df[~_target_null].reset_index(drop=True)\n"
            "y = df[TARGET].copy()\n"
            "X = df.drop(columns=[TARGET])\n"
            if tgt else "X = df.copy()\n"
        )
        + "\n"
        "print('Feature matrix shape:', X[num_feats + cat_feats_ohe].shape)"
    )
    cells.append(_code(fe_code))

    # ── 7. Model training & comparison ───────────────────────────────────
    if not eda_only and tgt:
        cells.append(_md(f"## 7. Model training\n\n"
                         f"Task: **{task_type or 'classification'}**"))

        if train:
            metrics_md = _fmt_metrics(train.get("metrics", {}))
            model_path = train.get("model_path")
            cells.append(_md(
                f"### 7a. Pipeline run results\n\n"
                f"- Estimator: `{train.get('estimator', 'RandomForest')}`\n"
                f"- n_train / n_test: **{train.get('n_train')} / {train.get('n_test')}**\n\n"
                f"**Metrics:**\n\n{metrics_md}\n"
                + (f"\n- Model saved: `{model_path}`" if model_path else "")
            ))

        # Full model comparison cell
        if is_regression:
            comparison_code = (
                "from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor\n"
                "from sklearn.linear_model import Ridge\n"
                "from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error\n"
                "\n"
                "X_proc = preprocessor.fit_transform(X[num_feats + cat_feats_ohe])\n"
                "y_enc = pd.to_numeric(y, errors='coerce').fillna(y.median())\n"
                "X_tr, X_te, y_tr, y_te = train_test_split(X_proc, y_enc,\n"
                "    test_size=0.2, random_state=0)\n"
                "\n"
                "models = {\n"
                "    'Random Forest': RandomForestRegressor(n_estimators=200, random_state=0, n_jobs=-1),\n"
                "    'Gradient Boosting': GradientBoostingRegressor(n_estimators=200, random_state=0),\n"
                "    'Ridge': Ridge(),\n"
                "}\n"
                "results = []\n"
                "for name, m in models.items():\n"
                "    m.fit(X_tr, y_tr)\n"
                "    p = m.predict(X_te)\n"
                "    results.append({'model': name,\n"
                "        'MAE': mean_absolute_error(y_te, p),\n"
                "        'RMSE': np.sqrt(mean_squared_error(y_te, p)),\n"
                "        'R2': r2_score(y_te, p)})\n"
                "results_df = pd.DataFrame(results).set_index('model')\n"
                "print(results_df.sort_values('R2', ascending=False))\n"
                "\n"
                "# Pick best by R2\n"
                "best_name = results_df['R2'].idxmax()\n"
                "model = models[best_name]\n"
                "print(f'Best model: {best_name}')"
            )
        else:
            comparison_code = (
                "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n"
                "from sklearn.linear_model import LogisticRegression\n"
                "from sklearn.metrics import f1_score, accuracy_score\n"
                "from sklearn.preprocessing import LabelEncoder\n"
                "\n"
                "X_proc = preprocessor.fit_transform(X[num_feats + cat_feats_ohe])\n"
                "le = LabelEncoder()\n"
                "y_enc = le.fit_transform(y.fillna(y.mode()[0]))\n"
                "X_tr, X_te, y_tr, y_te = train_test_split(X_proc, y_enc,\n"
                "    test_size=0.2, random_state=0, stratify=y_enc)\n"
                "\n"
                "models = {\n"
                "    'Random Forest': RandomForestClassifier(n_estimators=200, random_state=0, n_jobs=-1),\n"
                "    'Gradient Boosting': GradientBoostingClassifier(n_estimators=200, random_state=0),\n"
                "    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=0),\n"
                "}\n"
                "results = []\n"
                "for name, m in models.items():\n"
                "    cv = cross_val_score(m, X_tr, y_tr, cv=StratifiedKFold(5),\n"
                "                        scoring='f1_macro', n_jobs=-1)\n"
                "    m.fit(X_tr, y_tr)\n"
                "    p = m.predict(X_te)\n"
                "    results.append({'model': name,\n"
                "        'cv_f1_macro': cv.mean(), 'cv_std': cv.std(),\n"
                "        'test_accuracy': accuracy_score(y_te, p),\n"
                "        'test_f1_macro': f1_score(y_te, p, average='macro')})\n"
                "results_df = pd.DataFrame(results).set_index('model')\n"
                "print(results_df.sort_values('test_f1_macro', ascending=False))\n"
                "\n"
                "# Pick best by test F1\n"
                "best_name = results_df['test_f1_macro'].idxmax()\n"
                "model = models[best_name]\n"
                "print(f'Best model: {best_name}')"
            )
        cells.append(_code(comparison_code))

        # ── 8. Evaluation ────────────────────────────────────────────────
        cells.append(_md("## 8. Model evaluation"))
        if is_regression:
            eval_code = (
                "pred = model.predict(X_te)\n"
                "print(f'MAE : {mean_absolute_error(y_te, pred):.4f}')\n"
                "print(f'RMSE: {np.sqrt(mean_squared_error(y_te, pred)):.4f}')\n"
                "print(f'R²  : {r2_score(y_te, pred):.4f}')\n"
                "\n"
                "fig, ax = plt.subplots(figsize=(7, 5))\n"
                "ax.scatter(y_te, pred, alpha=0.3, s=10, color='#4d7cc7')\n"
                "lims = [min(y_te.min(), pred.min()), max(y_te.max(), pred.max())]\n"
                "ax.plot(lims, lims, 'r--', lw=1)\n"
                f"ax.set_xlabel('Actual {tgt}'); ax.set_ylabel('Predicted')\n"
                "ax.set_title('Actual vs Predicted')\n"
                "plt.tight_layout(); plt.show()\n"
                "\n"
                "residuals = y_te - pred\n"
                "fig, ax = plt.subplots(figsize=(7, 4))\n"
                "ax.scatter(pred, residuals, alpha=0.3, s=10, color='#4d7cc7')\n"
                "ax.axhline(0, color='red', lw=1)\n"
                "ax.set_xlabel('Predicted'); ax.set_ylabel('Residual')\n"
                "ax.set_title('Residual plot')\n"
                "plt.tight_layout(); plt.show()"
            )
        else:
            eval_code = (
                "pred = model.predict(X_te)\n"
                "print('Classification report:')\n"
                "print(classification_report(y_te, pred, target_names=[str(c) for c in le.classes_]))\n"
                "\n"
                "# Confusion matrix\n"
                "cm = confusion_matrix(y_te, pred)\n"
                "fig, ax = plt.subplots(figsize=(8, 6))\n"
                "ConfusionMatrixDisplay(cm, display_labels=le.classes_).plot(ax=ax, cmap='Blues')\n"
                "ax.set_title(f'Confusion matrix — {best_name}')\n"
                "plt.tight_layout(); plt.show()\n"
                "\n"
                "# ROC-AUC (multiclass OvR)\n"
                "if hasattr(model, 'predict_proba'):\n"
                "    proba = model.predict_proba(X_te)\n"
                "    n_classes = len(le.classes_)\n"
                "    if n_classes == 2:\n"
                "        print(f'ROC-AUC: {roc_auc_score(y_te, proba[:, 1]):.4f}')\n"
                "    else:\n"
                "        auc = roc_auc_score(y_te, proba, multi_class='ovr', average='macro')\n"
                "        print(f'Macro OvR ROC-AUC: {auc:.4f}')"
            )
        cells.append(_code(eval_code))

        # ── 9. Feature importance ────────────────────────────────────────
        cells.append(_md("## 9. Feature importance"))
        cells.append(_code(
            "# Built-in importance (tree models)\n"
            "if hasattr(model, 'feature_importances_'):\n"
            "    # Reconstruct feature names from preprocessor\n"
            "    num_names = num_feats.copy()\n"
            "    try:\n"
            "        ohe_names = list(preprocessor.named_transformers_['cat']\n"
            "                        .named_steps['ohe']\n"
            "                        .get_feature_names_out(cat_feats_ohe))\n"
            "    except Exception:\n"
            "        ohe_names = [f'cat_{i}' for i in range(\n"
            "            len(model.feature_importances_) - len(num_names))]\n"
            "    all_feat_names = num_names + ohe_names\n"
            "    n = len(model.feature_importances_)\n"
            "    imp = pd.Series(model.feature_importances_,\n"
            "                   index=all_feat_names[:n]).sort_values(ascending=False)\n"
            "    top_imp = imp.head(20)\n"
            "    fig, ax = plt.subplots(figsize=(8, 6))\n"
            "    top_imp.plot(kind='barh', ax=ax, color='#4d7cc7')\n"
            "    ax.invert_yaxis()\n"
            "    ax.set_title('Top-20 feature importances')\n"
            "    plt.tight_layout(); plt.show()\n"
            "    print(top_imp)\n"
            "else:\n"
            "    # Logistic Regression coefficients\n"
            "    if hasattr(model, 'coef_'):\n"
            "        coefs = np.abs(model.coef_).mean(axis=0)\n"
            "        imp = pd.Series(coefs).sort_values(ascending=False)\n"
            "        print('Top coefficient magnitudes:')\n"
            "        print(imp.head(20))"
        ))

        # ── 10. SHAP ─────────────────────────────────────────────────────
        cells.append(_md("## 10. SHAP explainability"))
        cells.append(_code(
            "try:\n"
            "    import shap\n"
            "    sample_size = min(300, len(X_te))\n"
            "    X_shap = X_te[:sample_size]\n"
            "    explainer = shap.TreeExplainer(model)\n"
            "    sv = explainer.shap_values(X_shap)\n"
            "    if isinstance(sv, list):\n"
            "        # Multiclass: show class with most variation\n"
            "        sv_plot = sv[0]\n"
            "    else:\n"
            "        sv_plot = sv\n"
            "    shap.summary_plot(sv_plot, X_shap,\n"
            "                     feature_names=all_feat_names[:X_shap.shape[1]])\n"
            "    plt.title('SHAP summary — beeswarm')\n"
            "    plt.tight_layout(); plt.show()\n"
            "    # Bar chart\n"
            "    shap.summary_plot(sv_plot, X_shap, plot_type='bar',\n"
            "                     feature_names=all_feat_names[:X_shap.shape[1]])\n"
            "except Exception as e:\n"
            "    print(f'SHAP skipped: {e}')"
        ))

        # ── 11. MLflow model registration ────────────────────────────────
        cells.append(_md("## 11. MLflow model registration"))
        cells.append(_code(
            "import mlflow, mlflow.sklearn\n"
            "\n"
            "mlflow.set_experiment('ds-agent')\n"
            "with mlflow.start_run(run_name=f'best_{best_name.replace(\" \",\"_\")}'):\n"
            "    mlflow.log_params({'model': best_name, 'test_size': 0.2})\n"
            + ("    mlflow.log_metrics({'r2': r2_score(y_te, pred),\n"
               "                        'mae': mean_absolute_error(y_te, pred),\n"
               "                        'rmse': float(np.sqrt(mean_squared_error(y_te, pred)))})\n"
               if is_regression else
               "    mlflow.log_metrics({'accuracy': accuracy_score(y_te, pred),\n"
               "                        'f1_macro': f1_score(y_te, pred, average='macro')})\n")
            + "    mlflow.sklearn.log_model(model, artifact_path='model',\n"
            "                              registered_model_name='ds-agent-model')\n"
            "    run_id_mlflow = mlflow.active_run().info.run_id\n"
            "    print(f'MLflow run_id: {run_id_mlflow}')"
        ))

        # ── 12. Deployment-ready inference snippet ────────────────────────
        cells.append(_md("## 12. Deployment — serve predictions"))
        cells.append(_code(
            "import joblib, json\n"
            "from pathlib import Path\n"
            "\n"
            "# Save model + preprocessor together\n"
            "model_bundle = {'model': model, 'preprocessor': preprocessor,\n"
            "                 'target': TARGET, 'feature_names': num_feats + cat_feats_ohe}\n"
            "joblib.dump(model_bundle, 'model_bundle.pkl')\n"
            "print('Saved model_bundle.pkl')\n"
            "\n"
            "# FastAPI snippet — copy into a new file and run with uvicorn\n"
            "fastapi_code = '''\n"
            "from fastapi import FastAPI\n"
            "import joblib, pandas as pd\n"
            "bundle = joblib.load('model_bundle.pkl')\n"
            "app = FastAPI()\n"
            "@app.get('/health')\n"
            "def health(): return {'status': 'ok'}\n"
            "@app.post('/predict')\n"
            "def predict(data: dict):\n"
            "    df = pd.DataFrame([data])\n"
            "    X = bundle['preprocessor'].transform(df[bundle['feature_names']])\n"
            "    pred = bundle['model'].predict(X)\n"
            "    return {'prediction': pred[0].item()}\n"
            "# Run: uvicorn serve:app --reload\n"
            "'''\n"
            "Path('serve.py').write_text(fastapi_code.strip())\n"
            "print('Created serve.py — run with: uvicorn serve:app --reload')"
        ))

    # ── EDA-only: auto-target inference cell ─────────────────────────────
    if eda_only:
        candidates = _guess_targets(artifacts)
        candidate_list = "\n".join(f"#   {c}" for c in candidates)
        cells.append(_md(
            "## 7. Auto-target selection\n\n"
            "The pipeline ran in EDA-only mode. The cell below infers the best target "
            "column automatically from column statistics — no manual input needed."
        ))
        cells.append(_code(
            "# Auto-select target from column statistics\n"
            "import re\n\n"
            "_TARGET_KEYWORDS = [\n"
            "    'outcome', 'result', 'target', 'label', 'class', 'status', 'flag',\n"
            "    'response', 'death', 'survived', 'churn', 'fraud', 'default',\n"
            "    'failure', 'success', 'risk', 'grade', 'category', 'event',\n"
            "]\n"
            "_SKIP = {'id', 'date', 'time', 'month', 'year', 'created', 'index'}\n\n"
            "def _ok(col):\n"
            "    lo = col.lower()\n"
            "    return not any(s in lo for s in _SKIP) and 2 <= df[col].nunique() <= 50\n\n"
            "TARGET = None\n"
            "cols_lower = {c.lower(): c for c in df.columns}\n"
            "for kw in _TARGET_KEYWORDS:\n"
            "    if TARGET: break\n"
            "    if kw in cols_lower and _ok(cols_lower[kw]):\n"
            "        TARGET = cols_lower[kw]\n"
            "    else:\n"
            "        for lo, orig in cols_lower.items():\n"
            "            if kw in lo and _ok(orig):\n"
            "                TARGET = orig; break\n"
            "if not TARGET:\n"
            "    # fallback: lowest-cardinality non-skip column\n"
            "    cands = [c for c in df.columns if _ok(c)]\n"
            "    TARGET = min(cands, key=lambda c: df[c].nunique()) if cands else None\n\n"
            f"# Candidates identified during pipeline run:\n{candidate_list}\n\n"
            "print(f'Auto-selected target: {{TARGET}}')\n"
            "print(f'Value counts:\\n{{df[TARGET].value_counts().head(10)}}')"
        ))

    # ── Drift ─────────────────────────────────────────────────────────────
    if drift:
        drifted = [k for k, v in (drift.get("features") or {}).items()
                   if isinstance(v, dict) and v.get("drifted")]
        n_checked = drift.get("n_checked") or len(drift.get("features") or {})
        cells.append(_md(
            f"## Drift analysis\n\n"
            f"Checked **{n_checked}** features (first half vs second half of dataset).  \n"
            f"**{len(drifted)}** feature(s) show distribution shift: "
            f"`{drifted[:10]}`"
        ))
        cells.append(_code(
            "# Drift check (PSI / KS test)\n"
            "from scipy import stats\n"
            "n = len(df) // 2\n"
            "for col in num_cols[:10]:\n"
            "    a, b = df[col].iloc[:n].dropna(), df[col].iloc[n:].dropna()\n"
            "    stat, p = stats.ks_2samp(a, b)\n"
            "    flag = '⚠️ DRIFT' if p < 0.05 else 'ok'\n"
            "    print(f'{col:30s} KS={stat:.4f}  p={p:.4f}  {flag}')"
        ))

    # ── Notebook metadata ─────────────────────────────────────────────────
    nb = {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"name": "python3", "display_name": "Python 3",
                           "language": "python"},
            "language_info": {"name": "python", "version": "3.11"},
        },
        "cells": cells,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(nb, indent=1))
    return out_path


def _guess_targets(artifacts: dict[str, Any]) -> list[str]:
    """Suggest target candidates from profile: low-cardinality non-float columns."""
    prof = artifacts.get("profile", {})
    col_rows = prof.get("profile", []) if isinstance(prof, dict) else []
    candidates = []
    for info in (col_rows if isinstance(col_rows, list) else []):
        if not isinstance(info, dict):
            continue
        n_unique = info.get("n_unique", 999)
        dtype = str(info.get("dtype", ""))
        col = info.get("column", "")
        if col and n_unique and 2 <= int(n_unique) <= 20 and "float" not in dtype:
            candidates.append(col)
    return candidates[:8] or ["(run profiler first or inspect df.columns above)"]
